version: '3'

services:
  localstack:
    image: localstack/localstack
    ports:
      - '127.0.0.1:4566:4566' # LocalStack Gateway
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=sqs
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=YOUR_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY=YOUR_SECRET_ACCESS_KEY
    volumes:
      - '${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack'
      - /var/run/docker.sock:/var/run/docker.sock
      - ./localstack:/etc/localstack/init/ready.d
    healthcheck:
      test: 'curl -sf http://localhost:4566/_localstack/health | grep ''"sqs": "running"'' || exit 1'
      interval: 30s
      timeout: 10s
      retries: 5
